Repository swyp-fade/fade-frontend, pull requests merged in 2024-07, with the labels that each got.

#11 tailwindCSS Prettier Sort Plugin 적용
  .prettierrc
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#13 프로젝트 폴더 구조 구성
  src/assets/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/pages/index.ts
  src/routes/index.ts
  src/services/index.ts
  src/utils/index.ts
Labels: ⚙ Setting

#15 기본 Provider 생성 및 설정
  .eslintrc.cjs
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/layouts/RootLayout.tsx
  src/libs/axios.ts
  src/libs/queryclient.ts
  src/pages/NotFoundPage.tsx
  src/pages/Root/page.tsx
  src/pages/index.ts
  src/routes/index.ts
  src/routes/index.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: ⚙ Setting

#19 로그인 인증 구조 작성
  index.html
  package.json
  pnpm-lock.yaml
  src/__mock__/handlers.ts
  src/__mock__/utils.ts
  src/assets/fade_logo.png
  src/assets/kakao_login_medium_wide.png
  src/components/FadeLogo.tsx
  src/hooks/auth.ts
  src/index.css
  src/libs/axios.ts
  src/pages/Auth/KakaoCallback.tsx
  src/pages/Auth/SignOut.tsx
  src/pages/Root/page.tsx
  src/pages/Root/views/InitializeAccountView.tsx
  src/pages/Root/views/LoginView.tsx
  src/pages/Root/views/MainView.tsx
  src/pages/Root/views/components/Carousel.tsx
  src/pages/Root/views/components/KakaoLoginButton.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
  src/services/authAPI.ts
  src/stores/auth.ts
  src/types/User.ts
  src/utils/index.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
Labels: ✨ Feature, 📬 API

#24 통신 응답 및 오류 구조 설정
  src/__mock__/handlers.ts
  src/hooks/auth.ts
  src/pages/Auth/KakaoCallback.tsx
  src/pages/Auth/SignOut.tsx
  src/pages/GlobalErrorPage.tsx
  src/pages/Root/InitializeAcocunt/page.tsx
  src/pages/Root/Login/components/Carousel.tsx
  src/pages/Root/Login/components/KakaoLoginButton.tsx
  src/pages/Root/Login/page.tsx
  src/pages/Root/page.tsx
  src/pages/Root/views/MainView.tsx
  src/routes/index.tsx
  src/services/authAPI.ts
  src/stores/auth.ts
  src/types/User.ts
  src/types/loaderResponse.ts
  src/types/serviceError.ts
  src/utils/index.ts
  tsconfig.app.json
  vite.config.ts
Labels: ⚙ Setting, ✨ Feature, 📬 API, 🔨 Refactor

#25 계정 초기 설정 페이지 구현
  package.json
  pnpm-lock.yaml
  src/components/ui/Input.tsx
  src/components/ui/form.tsx
  src/pages/Root/InitializeAccount/page.tsx
  src/pages/Root/InitializeAcocunt/page.tsx
  src/routes/index.tsx
  src/types/serviceError.ts
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature, 📬 API

#27 메인 페이지 레이아웃 구현
  src/index.css
  src/layouts/AppLayout.tsx
  src/layouts/RootLayout.tsx
  src/pages/Root/page.tsx
  src/pages/Root/voteFAP/page.tsx
  src/routes/index.tsx
Labels: 🎨 Publising

#29 공통 레이아웃 UI 구현
  package.json
  pnpm-lock.yaml
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/hooks/useHeader.ts
  src/layouts/AppLayout.tsx
  src/pages/Root/voteFAP/page.tsx
  src/stores/header.ts
  tailwind.config.js
Labels: 🎨 Publising

#31 기본 페이지 생성 및 라우팅 설정 보완
  src/hooks/useHeader.ts
  src/layouts/AppLayout.tsx
  src/pages/Root/archive/page.tsx
  src/pages/Root/feed/page.tsx
  src/pages/Root/mypage/page.tsx
  src/pages/Root/page.tsx
  src/pages/Root/upload/page.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 🔨 Refactor

#33 사진 업로드 화면(UI) 작성
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/NavBar.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/components/ui/toogleButton.tsx
  src/constants/index.ts
  src/index.css
  src/layouts/AppLayout.tsx
  src/layouts/FlexibleLayout.tsx
  src/layouts/RootLayout.tsx
  src/pages/Root/_dialogs/SelectStyleDialog/dialog.tsx
  src/pages/Root/_dialogs/SelectStyleDialog/view.tsx
  src/pages/Root/_dialogs/UploadDialog/components/InputImageFile.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
  src/pages/Root/_dialogs/UploadDialog/view.tsx
  src/pages/Root/_dialogs/components/AnimatedDialog.tsx
  src/pages/Root/_dialogs/components/DialogOverlay.tsx
  src/pages/Root/_dialogs/components/StylesList.tsx
  src/pages/Root/upload/page.tsx
  src/routes/index.tsx
  src/types/outfitStyle.ts
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor

#35 사진 업로드 가이드 Bottom Sheet 구현
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/view.tsx
  src/pages/Root/_dialogs/components/AnimatedDialog.tsx
  src/pages/Root/_dialogs/components/DialogOverlay.tsx
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor

#37 사진 업로드 정책 화면 구현
  package.json
  pnpm-lock.yaml
  src/pages/Root/_dialogs/SelectStyleDialog/dialog.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadPolicyView.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
  src/pages/Root/_dialogs/components/AnimatedDialog.tsx
  src/pages/Root/_dialogs/components/DialogOverlay.tsx
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor, 🥰 Accessibility

#41 ToastProvider 렌더링 위치 변경
  src/App.tsx
  src/layouts/RootLayout.tsx
  src/pages/Root/_dialogs/SelectStyleDialog/dialog.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
Labels: 🐞 BugFix

#43 업로드 가이드 Bottom Sheet 구조 변경
  src/pages/Root/_dialogs/UploadDialog/components/InputImageFile.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
Labels: ✨ Feature, 🔨 Refactor

#47 신고 Bottom Sheet 구현
  src/components/AnimatedDialog.tsx
  src/layouts/FlexibleLayout.tsx
  src/pages/Root/voteFAP/components/ReportBottomSheet.tsx
  src/pages/Root/voteFAP/page.tsx
Labels: 🎨 Publising, ✨ Feature

#49 투표 방법 모달 구현
  src/components/AnimatedDialog.tsx
  src/pages/Root/voteFAP/components/HowToVoteModal.tsx
  src/pages/Root/voteFAP/page.tsx
Labels: 🎨 Publising, ✨ Feature

#53 스타일 선택 변경 사항 대응
  src/components/ui/toogleButton.tsx
Labels: 🎨 Publising, 🔨 Refactor

#55 착장 정보 필드 디자인 변경 대응
  src/components/AnimatedDialog.tsx
  src/pages/Root/_dialogs/UploadDialog/components/OutfitFieldSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor

#57 신고 텍스트필드 글자수 카운트 추가
  src/pages/Root/voteFAP/components/ReportBottomSheet.tsx
  src/pages/Root/voteFAP/page.tsx
Labels: 🎨 Publising, ✨ Feature

#59 Confirm 모달 구현
  src/components/AnimatedDialog.tsx
  src/components/ConfirmProvider.tsx
  src/layouts/RootLayout.tsx
  src/stores/confirm.ts
Labels: 🎨 Publising, ✨ Feature

#61 Promise-based Modal Pattern 리팩토링
  src/components/AnimatedDialog.tsx
  src/components/ConfirmModal.tsx
  src/components/ConfirmProvider.tsx
  src/components/ModalProvider.tsx
  src/components/NavBar.tsx
  src/hooks/modal.ts
  src/layouts/RootLayout.tsx
  src/pages/Root/_dialogs/SelectStyleDialog/view.tsx
  src/pages/Root/_dialogs/UploadDialog/components/InputImageFile.tsx
  src/pages/Root/_dialogs/UploadDialog/components/OutfitFieldSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
  src/pages/Root/voteFAP/components/HowToVoteModal.tsx
  src/pages/Root/voteFAP/components/ReportBottomSheet.tsx
  src/pages/Root/voteFAP/components/VotePolicyBottomSheet.tsx
  src/pages/Root/voteFAP/page.tsx
  src/stores/modal.ts
Labels: 🎨 Publising, ✨ Feature, 🐞 BugFix, 🔨 Refactor

#63 Radix Dialog Escape Key 감지 인터셉트
  src/components/ModalProvider.tsx
  src/pages/Root/_dialogs/UploadDialog/components/InputImageFile.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
  src/stores/modal.ts
Labels: ✨ Feature, 🔨 Refactor, 🥰 Accessibility

#65 온보딩 화면 디자인 수정 대응
  src/assets/kakao_login.png
  src/assets/kakao_login_medium_wide.png
  src/assets/onboarding_background.jpg
  src/assets/onboarding_image_1.jpg
  src/assets/onboarding_image_2.jpg
  src/assets/onboarding_image_3.jpg
  src/pages/Root/Login/components/Carousel.tsx
  src/pages/Root/Login/components/KakaoLoginButton.tsx
  src/pages/Root/Login/page.tsx
Labels: 🎨 Publising, ✨ Feature

#67 서비스 이용 약관 화면 구현
  src/assets/checkIcon.svg
  src/pages/Auth/KakaoCallback.tsx
  src/pages/Root/signup/components/AgreementsView.tsx
  src/pages/Root/signup/components/InitializeAccountView.tsx
  src/pages/Root/signup/components/TermOfPIPA.tsx
  src/pages/Root/signup/components/TermOfService.tsx
  src/pages/Root/signup/page.tsx
  src/routes/index.tsx
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor

#69 계정 설정 페이지 디자인 수정
  package.json
  pnpm-lock.yaml
  src/__mock__/handlers.ts
  src/assets/fade_logo.png
  src/components/FadeLogo.tsx
  src/components/ui/Input.tsx
  src/pages/Root/signup/components/AgreementsView.tsx
  src/pages/Root/signup/components/InitializeAccountView.tsx
Labels: 🎨 Publising, 🔨 Refactor

#71 투표 탭 투표 기능 구현
  src/assets/swipe_fade_in.png
  src/assets/swipe_fade_out.png
  src/assets/test_fashion_image.jpg
  src/assets/test_fashion_image_10.jpg
  src/assets/test_fashion_image_2.jpg
  src/assets/test_fashion_image_3.jpg
  src/assets/test_fashion_image_4.jpg
  src/assets/test_fashion_image_5.webp
  src/assets/test_fashion_image_6.jpg
  src/assets/test_fashion_image_7.jpg
  src/assets/test_fashion_image_8.jpg
  src/assets/test_fashion_image_9.jpg
  src/assets/vote_ending_image.jpg
  src/assets/vote_starting_image.jpg
  src/pages/Root/voteFAP/components/ReadyToVoteView.tsx
  src/pages/Root/voteFAP/components/ReportBottomSheet.tsx
  src/pages/Root/voteFAP/components/RestartVotingView.tsx
  src/pages/Root/voteFAP/components/VoteController.tsx
  src/pages/Root/voteFAP/components/VotingView.tsx
  src/pages/Root/voteFAP/page.tsx
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature

#73 투표 방법 이미지 교체
  package.json
  pnpm-lock.yaml
  src/assets/how_to_vote_1.json
  src/assets/how_to_vote_2.png
  src/assets/how_to_vote_3.png
  src/pages/Root/voteFAP/components/HowToVoteModal.tsx
Labels: 🎨 Publising, 🔨 Refactor

#75 모달 종료 시 Interceptor 동작 수정
  src/components/ModalProvider.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
Labels: 🐞 BugFix

#77 투표 정보 Store 작성
  src/pages/Root/voteFAP/components/VoteController.tsx
  src/pages/Root/voteFAP/components/VotingView.tsx
  src/pages/Root/voteFAP/page.tsx
  src/stores/vote.ts
Labels: ✨ Feature, 🔨 Refactor

#79 Tailwind Foundation 수정
  tailwind.config.js
Labels: ⚙ Setting, 🎨 Publising

#81 SEO 관련 메타 정보 기입 (+PWA)
  index.html
  public/fade.webmanifest
  public/favicon.ico
  public/icons/apple-icon-114x114.png
  public/icons/apple-icon-120x120.png
  public/icons/apple-icon-144x144.png
  public/icons/apple-icon-152x152.png
  public/icons/apple-icon-180x180.png
  public/icons/apple-icon-57x57.png
  public/icons/apple-icon-60x60.png
  public/icons/apple-icon-72x72.png
  public/icons/apple-icon-76x76.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
  public/icons/icon_rounded.png
  public/icons/maskable_icon_x128.png
  public/icons/maskable_icon_x192.png
  public/icons/maskable_icon_x384.png
  public/icons/maskable_icon_x48.png
  public/icons/maskable_icon_x512.png
  public/icons/maskable_icon_x72.png
  public/icons/maskable_icon_x96.png
  public/og-image.png
  public/robots.txt
  src/components/AnimatedDialog.tsx
  src/index.css
  src/layouts/AppLayout.tsx
  src/layouts/RootLayout.tsx
  src/pages/Root/Login/components/Carousel.tsx
  src/pages/Root/voteFAP/components/ReadyToVoteView.tsx
  src/pages/Root/voteFAP/components/RestartVotingView.tsx
  src/pages/Root/voteFAP/components/VotingView.tsx
  tailwind.config.js
Labels: ⚙ Setting, 🔨 Refactor, 🥰 Accessibility

#83 MVP 배포를 위한 develop 코드 정리
  src/main.tsx
  src/pages/Root/_dialogs/SelectStyleDialog/dialog.tsx
  src/pages/Root/_dialogs/UploadDialog/components/SelectStyleView.tsx
  src/pages/Root/_dialogs/UploadDialog/components/StylesList.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/stores/header.ts
Labels: 🌏 Deploy, 🔨 Refactor

#91 모바일 환경 터치 피드백 개선
  src/assets/kakao_login@2x.png
  src/components/ConfirmModal.tsx
  src/components/NavBar.tsx
  src/components/ui/toogleButton.tsx
  src/layouts/RootLayout.tsx
  src/pages/Root/Login/components/KakaoLoginButton.tsx
  src/pages/Root/_dialogs/UploadDialog/components/InputImageFile.tsx
  src/pages/Root/_dialogs/UploadDialog/components/OutfitFieldSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/SelectStyleView.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadPolicyView.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
  src/pages/Root/login/components/Carousel.tsx
  src/pages/Root/login/components/KakaoLoginButton.tsx
  src/pages/Root/login/page.tsx
  src/pages/Root/signup/components/AgreementsView.tsx
  src/pages/Root/signup/components/InitializeAccountView.tsx
  src/pages/Root/signup/components/TermOfPIPA.tsx
  src/pages/Root/signup/components/TermOfService.tsx
  src/pages/Root/signup/page.tsx
  src/pages/Root/voteFAP/components/HowToVoteModal.tsx
  src/pages/Root/voteFAP/components/ReadyToVoteView.tsx
  src/pages/Root/voteFAP/components/ReportBottomSheet.tsx
  src/pages/Root/voteFAP/components/RestartVotingView.tsx
  src/pages/Root/voteFAP/components/VotePolicyBottomSheet.tsx
  src/pages/Root/voteFAP/components/VotingView.tsx
  src/pages/Root/voteFAP/page.tsx
  src/routes/index.tsx
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor, 🥰 Accessibility

#93 온보딩 페이지 PWA 환경 대응
  src/layouts/RootLayout.tsx
  src/pages/Root/login/components/Carousel.tsx
  src/pages/Root/login/page.tsx
Labels: 🎨 Publising, 🔨 Refactor

#96 API 실패 응답 핸들링 로직 작성
  index.html
  src/__mock__/handlers.ts
  src/pages/Auth/KakaoCallback.tsx
  src/pages/Root/page.tsx
  src/routes/index.tsx
  src/services/authAPI.ts
  src/types/serviceError.ts
  src/utils/index.ts
Labels: 📬 API, 🔨 Refactor

#97 Auth API 관련 로직 구현
  src/__mock__/handlers.ts
  src/components/AsyncErrorBoundary.tsx
  src/components/ui/toast.tsx
  src/layouts/RootLayout.tsx
  src/pages/GlobalErrorPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/Root/signup/components/InitializeAccountView.tsx
  src/pages/Root/signup/page.tsx
  src/routes/index.tsx
  src/services/authAPI.ts
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature, 📬 API, 🔨 Refactor

#99 사진 업로드 API 연동
  package.json
  pnpm-lock.yaml
  src/__mock__/handlers.ts
  src/components/ModalProvider.tsx
  src/pages/Auth/KakaoCallback.tsx
  src/pages/Auth/SignOut.tsx
  src/pages/Root/_dialogs/UploadDialog/components/InputImageFile.tsx
  src/pages/Root/_dialogs/UploadDialog/components/OutfitFieldSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/pages/Root/_dialogs/UploadDialog/dialog.tsx
  src/pages/Root/page.tsx
  src/pages/Root/signup/components/InitializeAccountView.tsx
  src/services/auth.ts
  src/services/feed.ts
  src/services/upload.ts
  src/stores/modal.ts
  src/utils/index.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#101 투표 선택지 목록 조회 API 연동
  src/__mock__/handlers.ts
  src/pages/Root/login/components/Carousel.tsx
  src/pages/Root/voteFAP/components/RandomAvatar.tsx
  src/pages/Root/voteFAP/components/VoteController.tsx
  src/pages/Root/voteFAP/components/VotingView.tsx
  src/pages/Root/voteFAP/page.tsx
  src/services/vote.ts
  src/stores/vote.ts
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature, 📬 API, 🔨 Refactor

#103 아카이브 탭 레이아웃 구현
  src/layouts/FlexibleLayout.tsx
  src/pages/Root/archive/dateStyle.css
  src/pages/Root/archive/page.tsx
  src/pages/Root/voteFAP/page.tsx
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature

#105 구독 탭 레이아웃 화면 작성
  src/components/NavBar.tsx
  src/pages/GlobalErrorPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadGuideBottomSheet.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/pages/Root/_dialogs/UploadDialog/components/UploadPolicyView.tsx
  src/pages/Root/feed/page.tsx
  src/pages/Root/signup/components/InitializeAccountView.tsx
  src/pages/Root/signup/components/TermOfPIPA.tsx
  src/pages/Root/signup/components/TermOfService.tsx
  src/pages/Root/subscribe/page.tsx
  src/pages/Root/voteFAP/components/VotePolicyBottomSheet.tsx
  src/routes/index.tsx
  tailwind.config.js
Labels: 🎨 Publising, ✨ Feature, 🔨 Refactor

#107 익명 이름 목록 변경
  src/utils/index.ts
Labels: 🔨 Refactor

#110 마이페이지/계정 관리/회원 탈퇴 화면 작성
  src/components/ConfirmModal.tsx
  src/pages/Root/mypage/components/AccountSetting.tsx
  src/pages/Root/mypage/components/ResignServiceView.tsx
  src/pages/Root/mypage/page.tsx
Labels: 🎨 Publising, ✨ Feature

#112 알림 페이지 화면 구현
  src/components/NotificationDialog.tsx
  src/components/ShowNotificationButton.tsx
  src/pages/Root/archive/page.tsx
  src/pages/Root/mypage/page.tsx
  src/pages/Root/subscribe/page.tsx
  src/pages/Root/voteFAP/page.tsx
  src/types/notification.ts
  src/utils/index.ts
Labels: 🎨 Publising, ✨ Feature

#114 패션 전체보기 필터 Dialog 작성
  src/pages/Root/archive/components/SelectFilterDialog.tsx
  src/pages/Root/archive/page.tsx
Labels: 🎨 Publising, ✨ Feature

#116 계정 검색 UI 구현
  src/hooks/useDebounce.ts
  src/pages/Root/archive/components/SearchAccountView.tsx
  src/pages/Root/archive/page.tsx
Labels: 🎨 Publising, ✨ Feature

#118 구독 목록 UI 구현
  src/pages/Root/subscribe/components/SubscribeListView.tsx
  src/pages/Root/subscribe/page.tsx
Labels: 🎨 Publising, ✨ Feature

#120 계정 상세 UI 컴포넌트 구현
  src/components/AccountProfileView.tsx
  src/pages/Root/subscribe/components/SubscribeListView.tsx
  src/pages/Root/subscribe/page.tsx
Labels: 🎨 Publising, ✨ Feature

#123 프로필 소개 편집 Bottom Sheet 구현 & 서브 페이지 접근 흐름 변경
  src/components/ProfileDetails.tsx
  src/components/ProfileIntroEditBottomSheet.tsx
  src/pages/Root/mypage/feed/page.tsx
  src/pages/Root/mypage/page.tsx
  src/pages/Root/subscribe/list/page.tsx
  src/pages/Root/subscribe/page.tsx
  src/pages/Root/user/page.tsx
  src/routes/index.tsx
Labels: 🎨 Publising, ✨ Feature, 🐞 BugFix, 🔨 Refactor

#125 북마크 화면 구현
  src/pages/Root/mypage/bookmark/page.tsx
  src/routes/index.tsx
Labels: 🎨 Publising, ✨ Feature

#129 투표 내역 화면 작성
  src/components/Header.tsx
  src/pages/Root/mypage/page.tsx
  src/pages/Root/mypage/voteHistory/dateStyle.css
  src/pages/Root/mypage/voteHistory/page.tsx
  src/routes/index.tsx
Labels: 🎨 Publising, ✨ Feature

#132 어제의 FA:P 모달 구현
  src/assets/fap_badge.png
  src/assets/fap_bg.jpg
  src/pages/Root/archive/components/LastFAPModal.tsx
  src/pages/Root/archive/page.tsx
Labels: 🎨 Publising, ✨ Feature

#134 서비스 lock 화면 구현
  src/components/LockUI.tsx
  src/components/Tooltip.tsx
Labels: 🎨 Publising, ✨ Feature

#141 FA:P 아카이브 조회 API 연동
  src/__mock__/handlers.ts
  src/__mock__/utils.ts
  src/pages/Root/archive/page.tsx
  src/services/feed.ts
  src/types/model.ts
Labels: 🎨 Publising, ✨ Feature, 📬 API, 🔨 Refactor

#143 패션 전체보기 조회 API 연동
  src/__mock__/handlers.ts
  src/__mock__/utils.ts
  src/hooks/useInfiniteObserver.ts
  src/pages/Root/archive/components/AllArchivingView.tsx
  src/pages/Root/archive/components/FAPArchivingView.tsx
  src/pages/Root/archive/components/SelectFilterDialog.tsx
  src/pages/Root/archive/components/dateStyle.css
  src/pages/Root/archive/page.tsx
  src/services/feed.ts
  src/types/model.ts
  src/types/response.ts
  src/utils/index.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#148 사진 상세 화면 작성 및 API 연동 & 구독 탭 API 연동 & 사진 상세 다이얼로그 연동
  src/__mock__/handlers.ts
  src/__mock__/utils.ts
  src/components/BookmarkButton.tsx
  src/components/FeedDetailCard.tsx
  src/components/FeedDetailDialog.tsx
  src/components/OutfitCard.tsx
  src/components/SubscribeButton.tsx
  src/components/ui/image.tsx
  src/hooks/useHeader.ts
  src/hooks/useInfiniteObserver.ts
  src/pages/Root/_dialogs/UploadDialog/components/UploadImageForm.tsx
  src/pages/Root/archive/components/AllArchivingView.tsx
  src/pages/Root/archive/components/FAPArchivingView.tsx
  src/pages/Root/subscribe/list/page.tsx
  src/pages/Root/subscribe/page.tsx
  src/pages/Root/voteFAP/components/VotingView.tsx
  src/services/feed.ts
  src/services/member.ts
  src/types/model.ts
Labels: 🎨 Publising, ✨ Feature, 📬 API, 🔨 Refactor

#150 계정 피드 페이지 API 연동
  src/__mock__/handlers.ts
  src/__mock__/utils.ts
  src/components/ProfileDetails.tsx
  src/components/ui/grid.tsx
  src/pages/Root/user/page.tsx
  src/services/feed.ts
  src/services/member.ts
  src/types/model.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#152 북마크 조회 API 연동
  src/pages/Root/mypage/bookmark/page.tsx
  src/pages/Root/mypage/feed/page.tsx
  src/services/feed.ts
Labels: 📬 API, 🔨 Refactor

#154 투표 내역 API 연동(미해결)
  src/__mock__/handlers.ts
  src/__mock__/utils.ts
  src/components/ui/button.tsx
  src/pages/Root/mypage/feed/page.tsx
  src/pages/Root/mypage/voteHistory/page.tsx
  src/services/vote.ts
  src/types/model.ts
  src/types/response.ts
Labels: 🎨 Publising, ✨ Feature, 📬 API, 🔨 Refactor

#156 자잘한 버그 수정
  src/components/FeedDetailCard.tsx
  src/components/FeedDetailDialog.tsx
  src/components/ProfileDetails.tsx
  src/components/SpinLoading.tsx
  src/hooks/useInfiniteObserver.ts
  src/pages/Root/archive/components/AllArchivingView.tsx
  src/pages/Root/archive/page.tsx
  src/pages/Root/mypage/bookmark/page.tsx
  src/pages/Root/mypage/voteHistory/page.tsx
  src/pages/Root/subscribe/list/page.tsx
  src/pages/Root/subscribe/page.tsx
Labels: 🐞 BugFix

#160 배포 HOTFIX3
  index.html
Labels: 🌏 Deploy, 🐞 BugFix

#164 API Mocking 버튼 추가
  package.json
  pnpm-lock.yaml
  src/components/MockingButton.tsx
  src/components/ui/button.tsx
  src/layouts/RootLayout.tsx
  src/pages/Root/login/page.tsx
Labels: 📬 API, ✅ Test

#167 API Mocking 버튼 미동작 수정
  src/main.tsx
Labels: 🐞 BugFix

#170 로그인 성공 이후 Authorization Header 추가
  src/libs/axios.ts
  src/pages/Auth/SignOut.tsx
  src/pages/Root/page.tsx
Labels: 📬 API, 🔨 Refactor

#174 배포 HOTFIX
  src/components/forms/account/_accountSchema.ts
  src/components/forms/account/fields/AccountIdField.tsx
Labels: 🐞 BugFix
